version: '3.8'

services:
  berutu-portfolio:
    build: .
    container_name: berutu-portfolio
    restart: unless-stopped
    ports:
      - "4321:4321"
    volumes:
      - berutu-data:/app/data
    env_file:
      - .env
    networks:
      - web

volumes:
  berutu-data:

networks:
  web:
    external: true
